### ISSUE TITLE
Unclear statement in manual

### ISSUE THREAD

**Issue by adittmar** [bitmotion/auth0-for-typo3#1]
Hello

This is rather a unclear statement in the manual than a bug:

- https://github.com/bitmotion/auth0-for-typo3/blob/master/README.md#global-configuration

- There is stated: 

> You have to add following parameters to the ['FE][cacheHash][excludedParameters] option: code and state.
> On the first installation, the extension will do that for you.

1. As far as I can see, the extension doesn't add those parameters automatically
2. Since this doesn't happen, it's also not clear to do this manually or not. Perhaps it was once needed in an older version of the extension or with a specific TYPO3 core version..

Suggestion: revise this part in the manual and remove the statement that the extension does this for the admin. Rather provide a code snippet how it need to be done manually. Otherwise the chapter can be removed of course, if not required at all :-)

Thanks and best regards
Andre

**Comment by LeuchtfeuerDigitalMarketing** [comment]
Hello Andre,

thanks for your interest in auth0!
We looked into this issue and the excludedParams are automatically set in the
LocalConfiguration.php by using the Signal Slot "afterExtensionInstall".

This actually works when installing the extension in the backend via the
extension manager.
However, this slot doesn't seem to be called when installing the extension via
composer. Are you running your TYPO3 with composer and helhum/typo3-console?

The actual problem here is, that the "afterExtensionInstall" signal is not
emitted when extensions are installed this way, so we would ask it you can
redirect this issue to [1]https://github.com/TYPO3-Console/TYPO3-Console.

Best regards
Andreas

------------------------------------------------------------------
Bitmotion GmbH
Immengarten 16-18 // 30177 Hannover // Germany
Amtsgericht Hannover HRB 59900 // GF: E. Guembel, T. Esders
------------------------------------------------------------------

06.09.2019 14:09 - Andre Dittmar schrieb:  

Hello

This is rather a unclear statement in the manual than a bug:

 - 

[2]https://github.com/bitmotion/auth0-for-typo3/blob/master/README.md#global-configuration

 - 

There is stated:

You have to add following parameters to the
['FE][cacheHash][excludedParameters] option: code and state.
On the first installation, the extension will do that for you.

 - As far as I can see, the extension doesn't add those parameters
automatically 
 - Since this doesn't happen, it's also not clear to do this manually or not.
Perhaps it was once needed in an older version of the extension or with a
specific TYPO3 core version.. 

Suggestion: revise this part in the manual and remove the statement that the
extension does this for the admin. Rather provide a code snippet how it need
to be done manually. Otherwise the chapter can be removed of course, if not
required at all :-)

Thanks and best regards
Andre

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, [3]view it on GitHub, or [4]mute the thread.



[1] https://github.com/TYPO3-Console/TYPO3-Console
[2] https://github.com/bitmotion/auth0-for-typo3/blob/master/README.md#global-configuration
[3] https://github.com/bitmotion/auth0-for-typo3/issues/1?email_source=notifications&amp;email_token=AE24QRPCWMPEO4MB7U53433QIJBWLA5CNFSM4IUII5S2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HJZIHOA

**Comment by flossels** [comment]
Hi all,

we should keep in mind, that setting excluded parameters this way is rather a dirty hack than a long term and recommended solution. It is on our agenda to solve this problem in a different way. However, the signal should be emitted by the console.
