### ISSUE TITLE
Question : Is there a timeframe for frontend login support in TYPO3 v11?

### ISSUE THREAD

**Issue by maximeMckayTurgeon** [bitmotion/auth0-for-typo3#37]
We are currently upgrading one of our projects to TYPO3 v11. That project's frontend authentication happens to be reliant on auth0-for-typo3. 

Can you estimate when we can expect the frontend login to be functional in TYPO3 v11? 

Thank you.

**Comment by LF-Grosser** [comment]
Sorry, there is currently no exact schedule for the reintegration of the frontend login. But this could change as soon as we get concrete requirements from our own projects. The functionality is in any case not off the table and should also be included in the versions for TYPO3 11 LTS and TYPO3 12 LTS.

Otherwise, we are of course also happy about support in the form of pull requests. This could also speed up the provision of the functionality.

**Comment by bastiwasni** [comment]
If anyone is struggling with updating to v11, feel free to contact me. I have a working version, but it has several client specific changes in it, so I am not able to share it with the community. Unfortunately I have not time to declutter this. It also runs only on a PHP 7.4 system, so I don't know if it's easy to upgrade to PHP 8.

Just in case somebody needs help to get the frontend login to work.
